### ISSUE TITLE
user can create an entry

### ISSUE THREAD

**Issue by AaronHe09** [Edward-J-Kim/code-journal-react#1]
## 💰 Motivation

Coders will want to capture tidbits they pick up during their research.

## 📐 Plan

Create a responsive form that allows users to store an image URL with some notes about a specific topic.

## 🖼️ Wireframes

![user can create an entry mobile](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/figma/user-can-create-an-entry-mobile.png)
![user can create an entry desktop](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/figma/user-can-create-an-entry-desktop.png)

## ✅ Task List

- [ ] Create a new component called header in the app container
- [ ] Create a new component for the form with the following layout:
  - [ ] a default placeholder image
  - [ ] a input for the image url
  - [ ] a input for the title
  - [ ] a textbox for the notes
- [ ] Make all inputs of the journal entry form `required`.
- [ ] Add an `'input'` onSubmit to the Photo URL input that stores the value of the input in a state called imageURL
- [ ] add a conditional statement that sets images src to equal the value of imageURL if its not an empty string.
- [ ]
